In [1]:
import numpy as np

In [17]:
import pandas as pd

In [112]:
with open('seq_enz_data_split_500.npy', 'rb') as f:
    a = np.load(f)

In [113]:
with open('seq_non_enz_data_split_500.npy', 'rb') as f:
    b = np.load(f)

In [114]:
data = np.array(list(a)+list(b))

In [115]:
data.shape

(1199, 500)

In [116]:
a.shape

(600, 500)

In [37]:
target = list(np.zeros((600,1),dtype=int))+list(np.ones((599,1),dtype=int))  #+list(np.zeros_like(b,dtype=int))

In [21]:
dict_ = list(pd.Series(a[0]).unique())

In [22]:
dict_.index('M')

0

In [117]:
encoded_data = []
for i in data:
    tem = []
    for j in range(data.shape[1]):
        try:
            tem.append( dict_.index(i[j]) )
        except:
            tem.append(0)
    encoded_data.append(tem)

In [118]:
np.array(encoded_data).shape

(1199, 500)

In [26]:
# encoded_data[0]

In [90]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

In [89]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
from sklearn.model_selection import train_test_split

In [69]:
from sklearn.linear_model import LogisticRegression

In [70]:
from sklearn.ensemble import RandomForestRegressor

In [71]:
from sklearn import svm

In [72]:
from sklearn.naive_bayes import GaussianNB

In [79]:
from sklearn.neighbors import KNeighborsClassifier

In [119]:
X_train, X_test, y_train, y_test = train_test_split(encoded_data, target, test_size=0.20)

# DecisionTreeClassifier

In [120]:
model = DecisionTreeClassifier( random_state=786)
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.5333333333333333
0.5087719298245614
[[70 50]
 [62 58]]


# RandomForestClassifier

In [121]:
model = RandomForestClassifier(max_depth=6, random_state=786)
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

<ipython-input-121-b461f4cb27ca>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model = model.fit(X_train, y_train)


0.65
0.4999999999999999
[[114   6]
 [ 78  42]]


# GaussianNB

In [122]:
model = GaussianNB()
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.5833333333333334
0.5495495495495495
[[79 41]
 [59 61]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


# KNeighborsClassifier

In [123]:
model = KNeighborsClassifier(n_neighbors=3)
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

<ipython-input-123-9d14d3c8f84d>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  model = model.fit(X_train, y_train)


0.575
0.5
[[87 33]
 [69 51]]


# svm

In [124]:
model = svm.SVC()
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


0.6166666666666667
0.5
[[102  18]
 [ 74  46]]
